<?php


/**
 * * Implements hook_install()
 */
function image_style_quality_install() {

  // Get the sites global image quality.
  $site_image_quality = variable_get('image_jpeg_quality', 75);

  // Set our new global image jpeg quality variable.
  variable_set('image_style_quality_global_quality', $site_image_quality);

}


/**
 * Implements hook_image_styles_alter().
 */
function image_style_quality_init() {

  /**
   * We want to reset our sites global quality to match the one that
   * we have defined to be our global quality override.
   */
  _image_style_quality_reset_to_global();

}


/**
 * Implements hook_image_effect_info().
 */
function image_style_quality_image_effect_info() {

  $effects = array();

  // Define all the paramters of our new style.
  $effects['image_style_quality'] = array(
    'label' => t('Change Quality'),
    'help' => t('Define the image quality for JPEG manipulations. Ranges from 0 to 100. Higher values mean better image quality but bigger files.'),
    'effect callback' => '_image_style_quality_apply',
    'form callback' => '_image_style_quality_form',
    'dimensions passthrough' => TRUE,
  );

  return $effects;

}


/**
 * Implements hook_form_alter().
 */
function image_style_quality_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'system_image_toolkit_settings') {

    // Get the original element that holds the sites quality.
    $original_quality_element = &$form['image_toolkit_settings']['image_jpeg_quality'];

    // Create a new variable which stores our valid global quality.
    $new_quality_element = &$form['image_toolkit_settings']['image_style_quality_global_quality'];
    $new_quality_element = $original_quality_element;

    // Make the default value of the new quality element the correct variable.
    $new_quality_element['#default_value'] = variable_get('image_style_quality_global_quality', 75);

    // The old quality element no longer stores our valid global quality.
    $original_quality_element['#type'] = "hidden";

  }

}


/*
 * The configuration form used to ask the user what quality their image
 * should be.
 */
function _image_style_quality_form($data) {

  $form = array();

  // Collect the quality of our image style, keep the default 75.
  $form['quality'] = array(
    '#title' => t('Image Quality'),
    '#type' => 'textfield',
    '#default_value' => isset($data['quality']) ? $data['quality'] : 75,
    '#field_prefix' => '%',
    '#size' => 4,
    '#element_validate' => array('_image_style_quality_form_quality_validate'),
    '#required' => TRUE,
  );

  // Return our form to hook_image_effect_info.
  return $form;

}


/**
 * This function validates the percentage input by a user to two conditions,
 * it must be numeric and it must fall within 1 and 100.
 */
function _image_style_quality_form_quality_validate($element, &$form_state, $form) {

  // Get the value entered by the user.
  $value = $element['#value'];

  // Make sure we are dealing with a number.
  if (!is_numeric($value)) {
    form_set_error('quality', 'Please enter a percentage as a single digit, eg "70"');
  }

  // Make sure that number falls within a valid range.
  if ($value <= 0 || $value > 100) {
    form_set_error('quality', 'Please enter a percentage between 0 and 100.');
  }

}


/**
 * This function is called when the image is ready for proccessing. It
 * sets the sites quality setting to the percentage defined in our
 * image style.
 */
function _image_style_quality_apply(&$image, $data) {

  // Grab the quality from our image style.
  $image_style_quality = $data['quality'];

  // Set the sites internal quality to be the one defined by our image style.
  variable_set('image_jpeg_quality', $image_style_quality);

}


/**
 * This function resets the sites image quality back to the original global
 * quality defined in this module.
 */
function _image_style_quality_reset_to_global() {

  // We want to access the global configuration of the site.
  global $conf;

  $global_quality = $conf['image_style_quality_global_quality'];

  // If our sites jpeg quality is different from our global quality, update it.
  if ($global_quality != $conf['image_jpeg_quality']) {

    // Reset the websites image style quality to the one the user has defined.
    variable_set('image_jpeg_quality', $global_quality);

  }

}

